import cookieParser from "cookie-parser";
import cors from "cors";
import express from "express";
import helmet from "helmet";
import { env } from "./config/env.js";
import { authRoutes } from "./routes/auth-routes.js";
import { healthRoutes } from "./routes/health-routes.js";
import { requestIdMiddleware } from "./middleware/request-id.js";
import { requestLoggingMiddleware } from "./middleware/request-logging.js";
import { errorHandler } from "./middleware/error-handler.js";
import { profileRoutes, resumeRoutes } from "./routes/resume-routes.js";
import { jobRoutes, searchRoutes } from "./routes/job-routes.js";
import { applicationRoutes } from "./routes/application-routes.js";
import { savedJobRoutes } from "./routes/saved-job-routes.js";
import { analyticsRoutes } from "./modules/analytics/analytics.routes.js";
import { recommendationRoutes } from "./routes/recommendation-routes.js";
import { apiRateLimit, authRateLimit } from "./middleware/rate-limit.js";
import { getMetrics } from "./controllers/metrics-controller.js";
import { incrementMetric, observeDuration } from "./observability/metrics.js";

export const app = express();
app.disable("x-powered-by");
app.set("trust proxy", env.TRUST_PROXY);
app.use(helmet());
app.use(cors({ origin: env.CLIENT_URL, credentials: true }));
app.use(express.json({ limit: "1mb" }));
app.use(cookieParser());
app.use(requestIdMiddleware);
app.use((request, response, next) => {
  const startedAt = Date.now();
  response.on("finish", () => {
    const labels = { method: request.method, route: request.route?.path ?? "unmatched", status_code: String(response.statusCode) };
    incrementMetric("rolescout_http_requests_total", labels);
    observeDuration("rolescout_http_request_duration_seconds", Date.now() - startedAt, labels);
    if (response.statusCode >= 400) incrementMetric("rolescout_http_errors_total", labels);
  });
  next();
});
app.use(requestLoggingMiddleware);
app.use("/api/v1/health", healthRoutes);
app.get("/api/v1/metrics", getMetrics);
app.use("/api/v1", apiRateLimit);
app.use("/api/v1/auth", authRateLimit, authRoutes);
app.use("/api/v1/resumes", resumeRoutes);
app.use("/api/v1/profile", profileRoutes);
app.use("/api/v1/jobs", jobRoutes);
app.use("/api/v1/recommendations", recommendationRoutes);
app.use("/api/v1/searches", searchRoutes);
app.use("/api/v1/applications", applicationRoutes);
app.use("/api/v1/saved-jobs", savedJobRoutes);
app.use("/api/v1/analytics", analyticsRoutes);
app.use(errorHandler);
